# Generated by Django 5.0.2 on 2024-03-04 08:53

import django.db.models.deletion
import poc_demo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poc_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ref_id', models.CharField(default=poc_demo.models.generate_reference_id, max_length=36, unique=True)),
                ('Customer_name', models.CharField(max_length=30)),
                ('Features', models.CharField(blank=True, max_length=30)),
                ('Requested_date', models.DateTimeField(auto_now=True)),
                ('Remarks', models.CharField(blank=True, max_length=10)),
                ('Timeline', models.DateTimeField(auto_now=True)),
                ('Status', models.CharField(choices=[('1', 'Active'), ('2', 'inActive'), ('3', 'closed')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.TextField()),
                ('Created_date', models.DateTimeField(auto_now=True)),
                ('Status', models.CharField(choices=[('1', 'Active'), ('2', 'inActive'), ('3', 'closed')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Features_list', models.TextField()),
                ('Status', models.CharField(choices=[('1', 'Active'), ('2', 'inActive'), ('3', 'closed')], max_length=30)),
                ('POC_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poc_demo.poc_model')),
            ],
        ),
        migrations.CreateModel(
            name='Demo_remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Remarks', models.TextField()),
                ('Status', models.CharField(choices=[('1', 'Active'), ('2', 'inActive'), ('3', 'closed')], max_length=30)),
                ('Demo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poc_demo.poc_model')),
            ],
        ),
        migrations.CreateModel(
            name='Demo_feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Features_list', models.TextField()),
                ('Status', models.CharField(choices=[('1', 'Active'), ('2', 'inActive'), ('3', 'closed')], max_length=30)),
                ('Demo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poc_demo.poc_model')),
            ],
        ),
        migrations.CreateModel(
            name='Poc_remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Remarks', models.TextField()),
                ('Status', models.CharField(choices=[('1', 'Active'), ('2', 'inActive'), ('3', 'closed')], max_length=30)),
                ('Poc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poc_demo.poc_model')),
            ],
        ),
        migrations.AddField(
            model_name='poc_model',
            name='Product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poc_demo.product'),
        ),
        migrations.CreateModel(
            name='Demo_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ref_id', models.CharField(default=poc_demo.models.generate_reference_id, max_length=36, unique=True)),
                ('Customer_name', models.CharField(max_length=30)),
                ('Features', models.CharField(blank=True, max_length=30)),
                ('Requested_date', models.DateTimeField(auto_now=True)),
                ('Remarks', models.CharField(blank=True, max_length=30)),
                ('Timeline', models.DateTimeField(auto_now=True)),
                ('Status', models.CharField(choices=[('1', 'Active'), ('2', 'inActive'), ('3', 'closed')], max_length=30)),
                ('Product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poc_demo.product')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(default='abc@olatechs.com', max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('roles', models.CharField(choices=[('1', 'Admin'), ('2', 'Maanager'), ('3', 'sales')], max_length=30)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'inActive'), ('3', 'closed')], max_length=30)),
                ('logged_in', models.DateTimeField(auto_now_add=True)),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poc_demo.users')),
            ],
        ),
    ]
