# Generated by Django 5.0.4 on 2024-04-11 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poc_demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo_feature_status',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='demo_feature_status',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='demo_remark',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='demo_remark',
            name='demo_id',
        ),
        migrations.DeleteModel(
            name='Demo_feature',
        ),
        migrations.DeleteModel(
            name='Demo_Feature_status',
        ),
        migrations.DeleteModel(
            name='Demo_remark',
        ),
    ]
