# Generated by Django 5.0.2 on 2024-03-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc_demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='roles',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Manager'), ('3', 'sales')], max_length=30),
        ),
    ]
