# Generated by Django 5.0.4 on 2024-04-05 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc_demo', '0002_remove_poc_model_assign_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='poc_model',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
