# Generated by Django 5.0.2 on 2024-03-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc_demo', '0002_alter_users_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_by',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
