# Generated by Django 5.0.4 on 2024-04-11 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poc_demo', '0002_remove_demo_feature_status_feature_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo_model',
        ),
    ]
