# Generated by Django 5.0.2 on 2024-03-05 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc_demo', '0003_product_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'inActive'), ('3', 'closed')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poc_demo.roles'),
        ),
    ]
