# Generated by Django 5.0.4 on 2024-04-05 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poc_demo', '0003_poc_model_assign_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poc_model',
            name='assign_to',
        ),
    ]
