# Generated by Django 5.0.2 on 2024-03-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc_demo', '0004_roles_alter_users_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='added_by',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
