# Generated by Django 5.0.4 on 2024-04-11 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc_demo', '0004_demo_feature_demo_feature_status_demo_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demo_feature',
            old_name='poc_id',
            new_name='demo_id',
        ),
        migrations.AlterField(
            model_name='demo_remark',
            name='demo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demo_r_related', to='poc_demo.demo_model'),
        ),
    ]
