# Generated by Django 5.0.2 on 2024-03-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc_demo', '0005_roles_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='added_by',
            field=models.CharField(max_length=30),
        ),
    ]
