# Generated by Django 5.0.2 on 2024-03-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc_demo', '0006_alter_roles_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='poc_model',
            name='added_by',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
