# Generated by Django 5.0.2 on 2024-03-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poc_demo', '0008_alter_demo_model_features_alter_demo_model_remarks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='Features_list',
            new_name='features_list',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='POC_id',
            new_name='poc_id',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='poc_remark',
            old_name='Poc_id',
            new_name='poc_id',
        ),
        migrations.RenameField(
            model_name='poc_remark',
            old_name='Remarks',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='poc_remark',
            old_name='Status',
            new_name='status',
        ),
    ]
