# Generated by Django 5.0.2 on 2024-03-06 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc_demo', '0009_rename_features_list_feature_features_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('added_by', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='demo_model',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='poc_model',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Status',
        ),
        migrations.AlterField(
            model_name='demo_feature',
            name='Status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poc_demo.status'),
        ),
        migrations.AlterField(
            model_name='demo_remark',
            name='Status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poc_demo.status'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poc_demo.status'),
        ),
        migrations.AlterField(
            model_name='poc_remark',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poc_demo.status'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poc_demo.status'),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poc_demo.status'),
        ),
        migrations.AddField(
            model_name='demo_model',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poc_demo.status'),
        ),
        migrations.AddField(
            model_name='poc_model',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poc_demo.status'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poc_demo.status'),
        ),
    ]
