# Generated by Django 5.0.2 on 2024-03-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poc_demo', '0010_status_remove_demo_model_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demo_feature',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='demo_remark',
            old_name='Status',
            new_name='status',
        ),
    ]
