# Generated by Django 5.0.2 on 2024-03-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc_demo', '0011_rename_status_demo_feature_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poc_model',
            name='Requested_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
