# Generated by Django 5.0.2 on 2024-03-08 04:58

import poc_demo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc_demo', '0014_alter_demo_feature_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poc_model',
            name='Requested_date',
            field=models.DateField(default=poc_demo.models.get_default_date),
        ),
        migrations.AlterField(
            model_name='poc_model',
            name='Timeline',
            field=models.DateField(default=poc_demo.models.get_default_date),
        ),
    ]
