# Generated by Django 5.0.2 on 2024-03-08 05:02

import poc_demo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc_demo', '0015_alter_poc_model_requested_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo_model',
            name='Features',
        ),
        migrations.RemoveField(
            model_name='demo_model',
            name='Remarks',
        ),
        migrations.RemoveField(
            model_name='poc_model',
            name='Features',
        ),
        migrations.RemoveField(
            model_name='poc_model',
            name='Remarks',
        ),
        migrations.AlterField(
            model_name='demo_model',
            name='Requested_date',
            field=models.DateField(default=poc_demo.models.get_default_date),
        ),
        migrations.AlterField(
            model_name='demo_model',
            name='Timeline',
            field=models.DateField(default=poc_demo.models.get_default_date),
        ),
    ]
