# Generated by Django 5.0.2 on 2024-03-08 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc_demo', '0017_alter_poc_remark_poc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo_feature',
            name='added_by',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='demo_remark',
            name='added_by',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='feature',
            name='added_by',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='poc_remark',
            name='added_by',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='demo_feature',
            name='status',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='demo_remark',
            name='status',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='poc_remark',
            name='poc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poc_demo.poc_model'),
        ),
        migrations.AlterField(
            model_name='poc_remark',
            name='status',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='added_by',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
